const continents = {
  BD: 'Asia',
  BE: 'Europe',
  BF: 'Africa',
  BG: 'Europe',
  BA: 'Europe',
  BB: 'North America',
  WF: 'Australia',
  BL: 'North America',
  BM: 'North America',
  BN: 'Asia',
  BO: 'South East Asia',
  BH: 'Asia',
  BI: 'Africa',
  BJ: 'Africa',
  BT: 'Asia',
  JM: 'North America',
  BV: 'Antarctica',
  BW: 'Africa',
  WS: 'Australia',
  BQ: 'North America',
  BR: 'South East Asia',
  BS: 'North America',
  JE: 'Europe',
  BY: 'Europe',
  BZ: 'North America',
  RU: 'Europe',
  RW: 'Africa',
  RS: 'Europe',
  TL: 'Australia',
  RE: 'Africa',
  TM: 'Asia',
  TJ: 'Asia',
  RO: 'Europe',
  TK: 'Australia',
  GW: 'Africa',
  GU: 'Australia',
  GT: 'North America',
  GS: 'Antarctica',
  GR: 'Europe',
  GQ: 'Africa',
  GP: 'North America',
  JP: 'Asia',
  GY: 'South East Asia',
  GG: 'Europe',
  GF: 'South East Asia',
  GE: 'Asia',
  GD: 'North America',
  GB: 'Europe',
  GA: 'Africa',
  SV: 'North America',
  GN: 'Africa',
  GM: 'Africa',
  GL: 'North America',
  GI: 'Europe',
  GH: 'Africa',
  OM: 'Asia',
  TN: 'Africa',
  JO: 'Asia',
  HR: 'Europe',
  HT: 'North America',
  HU: 'Europe',
  HK: 'Asia',
  HN: 'North America',
  HM: 'Antarctica',
  VE: 'South East Asia',
  PR: 'North America',
  PS: 'Asia',
  PW: 'Australia',
  PT: 'Europe',
  SJ: 'Europe',
  PY: 'South East Asia',
  IQ: 'Asia',
  PA: 'North America',
  PF: 'Australia',
  PG: 'Australia',
  PE: 'South East Asia',
  PK: 'Asia',
  PH: 'Asia',
  PN: 'Australia',
  PL: 'Europe',
  PM: 'North America',
  ZM: 'Africa',
  EH: 'Africa',
  EE: 'Europe',
  EG: 'Africa',
  ZA: 'Africa',
  EC: 'South East Asia',
  IT: 'Europe',
  VN: 'Asia',
  SB: 'Australia',
  ET: 'Africa',
  SO: 'Africa',
  ZW: 'Africa',
  ES: 'Europe',
  ER: 'Africa',
  ME: 'Europe',
  MD: 'Europe',
  MG: 'Africa',
  MF: 'North America',
  MA: 'Africa',
  MC: 'Europe',
  UZ: 'Asia',
  MM: 'Asia',
  ML: 'Africa',
  MO: 'Asia',
  MN: 'Asia',
  MH: 'Australia',
  MK: 'Europe',
  MU: 'Africa',
  MT: 'Europe',
  MW: 'Africa',
  MV: 'Asia',
  MQ: 'North America',
  MP: 'Australia',
  MS: 'North America',
  MR: 'Africa',
  IM: 'Europe',
  UG: 'Africa',
  TZ: 'Africa',
  MY: 'Asia',
  MX: 'North America',
  IL: 'Asia',
  FR: 'Europe',
  IO: 'Asia',
  SH: 'Africa',
  FI: 'Europe',
  FJ: 'Australia',
  FK: 'South East Asia',
  FM: 'Australia',
  FO: 'Europe',
  NI: 'North America',
  NL: 'Europe',
  NO: 'Europe',
  NA: 'Africa',
  VU: 'Australia',
  NC: 'Australia',
  NE: 'Africa',
  NF: 'Australia',
  NG: 'Africa',
  NZ: 'Australia',
  NP: 'Asia',
  NR: 'Australia',
  NU: 'Australia',
  CK: 'Australia',
  XK: 'Europe',
  CI: 'Africa',
  CH: 'Europe',
  CO: 'South East Asia',
  CN: 'Asia',
  CM: 'Africa',
  CL: 'South East Asia',
  CC: 'Asia',
  CA: 'North America',
  CG: 'Africa',
  CF: 'Africa',
  CD: 'Africa',
  CZ: 'Europe',
  CY: 'Europe',
  CX: 'Asia',
  CR: 'North America',
  CW: 'North America',
  CV: 'Africa',
  CU: 'North America',
  SZ: 'Africa',
  SY: 'Asia',
  SX: 'North America',
  KG: 'Asia',
  KE: 'Africa',
  SS: 'Africa',
  SR: 'South East Asia',
  KI: 'Australia',
  KH: 'Asia',
  KN: 'North America',
  KM: 'Africa',
  ST: 'Africa',
  SK: 'Europe',
  KR: 'Asia',
  SI: 'Europe',
  KP: 'Asia',
  KW: 'Asia',
  SN: 'Africa',
  SM: 'Europe',
  SL: 'Africa',
  SC: 'Africa',
  KZ: 'Asia',
  KY: 'North America',
  SG: 'Asia',
  SE: 'Europe',
  SD: 'Africa',
  DO: 'North America',
  DM: 'North America',
  DJ: 'Africa',
  DK: 'Europe',
  VG: 'North America',
  DE: 'Europe',
  YE: 'Asia',
  DZ: 'Africa',
  US: 'North America',
  UY: 'South East Asia',
  YT: 'Africa',
  UM: 'Australia',
  LB: 'Asia',
  LC: 'North America',
  LA: 'Asia',
  TV: 'Australia',
  TW: 'Asia',
  TT: 'North America',
  TR: 'Asia',
  LK: 'Asia',
  LI: 'Europe',
  LV: 'Europe',
  TO: 'Australia',
  LT: 'Europe',
  LU: 'Europe',
  LR: 'Africa',
  LS: 'Africa',
  TH: 'Asia',
  TF: 'Antarctica',
  TG: 'Africa',
  TD: 'Africa',
  TC: 'North America',
  LY: 'Africa',
  VA: 'Europe',
  VC: 'North America',
  AE: 'Asia',
  AD: 'Europe',
  AG: 'North America',
  AF: 'Asia',
  AI: 'North America',
  VI: 'North America',
  IS: 'Europe',
  IR: 'Asia',
  AM: 'Asia',
  AL: 'Europe',
  AO: 'Africa',
  AQ: 'Antarctica',
  AS: 'Australia',
  AR: 'South East Asia',
  AU: 'Australia',
  AT: 'Europe',
  AW: 'North America',
  IN: 'Asia',
  AX: 'Europe',
  AZ: 'Asia',
  IE: 'Europe',
  ID: 'Asia',
  UA: 'Europe',
  QA: 'Asia',
  MZ: 'Africa',
};

module.exports = continents;
